#!/usr/bin/env python3
"""
Find two CA runs (possibly different rules) where the same visible window
cannot distinguish which rule or initial state was used.

Goal: make a diptych where both panels show the SAME visual region,
but one was generated by Rule 90 and one by Rule 150 — or more
interestingly, two panels that look identical but have different histories.

The conceptual point: completion-as-recognition (Rule 90 gap, one answer)
vs. genuine ambiguity (you cannot determine the rule from visible state alone).
"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def apply_rule(rule_num, row):
    """Apply elementary CA rule to a row."""
    n = len(row)
    rule_bits = [(rule_num >> i) & 1 for i in range(8)]
    new_row = np.zeros(n, dtype=int)
    for i in range(n):
        left = row[(i-1) % n]
        center = row[i]
        right = row[(i+1) % n]
        idx = (left << 2) | (center << 1) | right
        new_row[i] = rule_bits[idx]
    return new_row

def run_ca(rule_num, initial, steps):
    """Run CA for N steps, return array."""
    n = len(initial)
    grid = np.zeros((steps, n), dtype=int)
    grid[0] = initial
    for i in range(1, steps):
        grid[i] = apply_rule(rule_num, grid[i-1])
    return grid

# Width and steps
W = 201
STEPS = 200

# Rule 90 from single center cell
ic_90 = np.zeros(W, dtype=int)
ic_90[W//2] = 1
grid_90 = run_ca(90, ic_90, STEPS)

# Rule 150 from single center cell
ic_150 = np.zeros(W, dtype=int)
ic_150[W//2] = 1
grid_150 = run_ca(150, ic_150, STEPS)

# Rule 18: also produces Sierpinski-like pattern
ic_18 = np.zeros(W, dtype=int)
ic_18[W//2] = 1
grid_18 = run_ca(18, ic_18, STEPS)

# Rule 26: another pattern
ic_26 = np.zeros(W, dtype=int)
ic_26[W//2] = 1
grid_26 = run_ca(26, ic_26, STEPS)

# Find a visual window where Rule 90 and Rule 150 look similar
# Strategy: crop to a specific sub-region
# Rule 90 and Rule 150 both produce Sierpinski-like triangles
# but with different sub-structure

# Let's just show the full comparison and see what we get
fig, axes = plt.subplots(1, 4, figsize=(16, 8))
cmap = plt.cm.get_cmap('binary')

for ax, grid, label in zip(axes,
                           [grid_90, grid_150, grid_18, grid_26],
                           ['Rule 90', 'Rule 150', 'Rule 18', 'Rule 26']):
    ax.imshow(grid, cmap='binary', interpolation='nearest', aspect='auto')
    ax.set_title(label)
    ax.axis('off')

plt.tight_layout()
plt.savefig('/home/sprite/slop-salon-rahel/assets/ca-comparison.png', dpi=80)
print("saved ca-comparison.png")
plt.close()

# Now find regions that look visually similar between rules
# Look at the middle-right quadrant of Rule 90 vs different regions of other rules
# For a diptych, I want: two panels that look like the same pattern
# but were generated by different rules/ICs

# Approach: Rule 90 has triangular voids. Rule 150 has different void structure.
# Find a window where both have similar cell density and pattern type.

# Alternative: use the same rule but different random ICs
# And show a window from both that looks the same (or very different)
# making the point that the same visible state has multiple histories

rng = np.random.default_rng(42)

# Two different random initial conditions for Rule 90
ic_rand1 = rng.integers(0, 2, W)
ic_rand2 = rng.integers(0, 2, W)

grid_r1 = run_ca(90, ic_rand1, STEPS)
grid_r2 = run_ca(90, ic_rand2, STEPS)

# For Rule 30 (chaotic)
grid_r30_1 = run_ca(30, ic_rand1, STEPS)
grid_r30_2 = run_ca(30, ic_rand2, STEPS)

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
for ax, grid, label in zip(axes.flat,
                           [grid_r1, grid_r2, grid_r30_1, grid_r30_2],
                           ['Rule 90 (IC1)', 'Rule 90 (IC2)', 'Rule 30 (IC1)', 'Rule 30 (IC2)']):
    ax.imshow(grid, cmap='binary', interpolation='nearest', aspect='auto')
    ax.set_title(label)
    ax.axis('off')

plt.tight_layout()
plt.savefig('/home/sprite/slop-salon-rahel/assets/ca-random-comparison.png', dpi=80)
print("saved ca-random-comparison.png")
plt.close()
